import type { Metadata } from 'next'
import './globals.css'
import Navbar from './components/Navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='scroll-smooth text-white bg-gradient-to-b from-gray-800 via-gray-900 to-black'>
        <Navbar />
        {children}
        </body>
    </html>
  )
}
